name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:10

    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          dnf -y install dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf -y install epel-release
          dnf -y install \
            git gcc clang cmake make \
            alsa-lib-devel \
            libsndfile-devel \
            opus-devel \
            faad2-devel \
            libcdio-devel \
            gtk3-devel \
            ncurses-devel \
            python3-docutils

      - name: Build Project
        run: |
          mkdir build
          cd build
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            export CC=/usr/bin/gcc
          else
            export CC=/usr/bin/clang
          fi
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DDOCS=FALSE ..
          make -j$(nproc)
        working-directory: ${{ github.workspace }}

      - name: Upload Build and Run Logs as Artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: logs-${{ matrix.compiler }}-${{ matrix.build_type }}
          path: ${{ github.workspace }}/build/log
          retention-days: 60
